version: '3.11'

services:

  db:
    image: postgres:14
    container_name: db
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    command:
      -p 5432
    expose:
      - 5432
    env_file:
      - .env-non-dev

  project-dev:
    container_name: project-dev
    build:
      context: .
    command: ["/quizzesproject/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env-non-dev


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  db_data:
  pgadmin_data:
  redis_data: