services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    env_file:
      - .env-non-dev


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data
    depends_on:
      - db

  redis:
    image: redis:7
    container_name: redis
    command: redis-server
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"


  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"


  app:
    container_name: quizzesfastapi_app
    command: ["/quizzesproject/docker/app.sh"]
    build:
      context: .
    env_file:
      - .env-non-dev
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - mongo
    environment:
      - PYTHONPATH=/quizzesproject/src

volumes:
  db_data:
  pgadmin_data:
  redis_data: