"""application added

Revision ID: 3eb1eefad1e1
Revises: 599c34405b42
Create Date: 2024-09-05 19:30:41.421929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb1eefad1e1'
down_revision: Union[str, None] = '599c34405b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('invitation', 'status',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=False)
    op.drop_column('invitation', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('invitation', 'status',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=True)
    op.drop_table('application')
    # ### end Alembic commands ###
