"""mark fix update

Revision ID: ab147e4af989
Revises: f911f69a43ef
Create Date: 2024-09-11 23:50:19.877028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab147e4af989'
down_revision: Union[str, None] = 'f911f69a43ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_result', sa.Column('questions_overall', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_result', 'questions_overall')
    # ### end Alembic commands ###
