"""models updated

Revision ID: 49611ef59f3a
Revises: 1b67c6f3f11b
Create Date: 2024-09-24 21:39:21.498427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49611ef59f3a'
down_revision: Union[str, None] = '1b67c6f3f11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notification_user_id_fkey', 'notification', type_='foreignkey')
    op.drop_constraint('notification_company_id_fkey', 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notification', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quiz_result_user_id_fkey', 'quiz_result', type_='foreignkey')
    op.drop_constraint('quiz_result_company_id_fkey', 'quiz_result', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_result', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quiz_result', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_result', type_='foreignkey')
    op.drop_constraint(None, 'quiz_result', type_='foreignkey')
    op.create_foreign_key('quiz_result_company_id_fkey', 'quiz_result', 'company', ['company_id'], ['id'])
    op.create_foreign_key('quiz_result_user_id_fkey', 'quiz_result', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key('notification_company_id_fkey', 'notification', 'company', ['company_id'], ['id'])
    op.create_foreign_key('notification_user_id_fkey', 'notification', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
