"""notifications added

Revision ID: 109e78f2f293
Revises: ab147e4af989
Create Date: 2024-09-12 23:12:07.395354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109e78f2f293'
down_revision: Union[str, None] = 'ab147e4af989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_result', 'questions_overall',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_result', 'questions_overall',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
